# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QMainWindow
from widgets import LCDNumber, PushButton


class Ui_MainWindow(QMainWindow, object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = LCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(3, 2, 351, 51))
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_10 = PushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 60, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_17 = PushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 60, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = PushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 60, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_9 = PushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 140, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = PushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(180, 140, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = PushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(90, 140, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = PushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 140, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = PushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(270, 220, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = PushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(270, 300, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = PushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(270, 380, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_19 = PushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(180, 300, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = PushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(90, 300, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = PushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 300, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = PushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(180, 380, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = PushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(180, 220, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = PushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(90, 220, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = PushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 220, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = PushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(90, 380, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = PushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 380, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_8 = PushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 60, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menufile.addAction(self.actionSave)
        self.menubar.addAction(self.menufile.menuAction())
        self.actionSave.triggered.connect(self.save)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "*"))
        self.pushButton_17.setText(_translate("MainWindow", "<"))
        self.pushButton_18.setText(_translate("MainWindow", "C"))
        self.pushButton_9.setText(_translate("MainWindow", "+"))
        self.pushButton_11.setText(_translate("MainWindow", "3"))
        self.pushButton_12.setText(_translate("MainWindow", "2"))
        self.pushButton_13.setText(_translate("MainWindow", "1"))
        self.pushButton_14.setText(_translate("MainWindow", "-"))
        self.pushButton_15.setText(_translate("MainWindow", "%"))
        self.pushButton_16.setText(_translate("MainWindow", "="))
        self.pushButton_19.setText(_translate("MainWindow", "9"))
        self.pushButton_20.setText(_translate("MainWindow", "8"))
        self.pushButton_21.setText(_translate("MainWindow", "7"))
        self.pushButton_22.setText(_translate("MainWindow", ","))
        self.pushButton_23.setText(_translate("MainWindow", "6"))
        self.pushButton_24.setText(_translate("MainWindow", "5"))
        self.pushButton_25.setText(_translate("MainWindow", "4"))
        self.pushButton_26.setText(_translate("MainWindow", "0"))
        self.pushButton_27.setText(_translate("MainWindow", "!"))
        self.pushButton_8.setText(_translate("MainWindow", "/"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save "))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))

    def save(self):
        lcd_coords = str(self.lcdNumber.x()), str(self.lcdNumber.y())
        pushButton_coords_8 = str(self.pushButton_8.x()), str(self.pushButton_8.y())
        pushButton_coords_9 = str(self.pushButton_9.x()), str(self.pushButton_9.y())
        pushButton_coords_10 = str(self.pushButton_10.x()), str(self.pushButton_10.y())
        pushButton_coords_11 = str(self.pushButton_11.x()), str(self.pushButton_11.y())
        pushButton_coords_12 = str(self.pushButton_12.x()), str(self.pushButton_12.y())
        pushButton_coords_13 = str(self.pushButton_13.x()), str(self.pushButton_13.y())
        pushButton_coords_14 = str(self.pushButton_14.x()), str(self.pushButton_14.y())
        pushButton_coords_15 = str(self.pushButton_15.x()), str(self.pushButton_15.y())
        pushButton_coords_16 = str(self.pushButton_16.x()), str(self.pushButton_16.y())
        pushButton_coords_17 = str(self.pushButton_17.x()), str(self.pushButton_17.y())
        pushButton_coords_18 = str(self.pushButton_18.x()), str(self.pushButton_18.y())
        pushButton_coords_19 = str(self.pushButton_19.x()), str(self.pushButton_19.y())
        pushButton_coords_20 = str(self.pushButton_20.x()), str(self.pushButton_20.y())
        pushButton_coords_21 = str(self.pushButton_21.x()), str(self.pushButton_21.y())
        pushButton_coords_22 = str(self.pushButton_22.x()), str(self.pushButton_22.y())
        pushButton_coords_23 = str(self.pushButton_23.x()), str(self.pushButton_23.y())
        pushButton_coords_24 = str(self.pushButton_24.x()), str(self.pushButton_24.y())
        pushButton_coords_25 = str(self.pushButton_25.x()), str(self.pushButton_25.y())
        pushButton_coords_26 = str(self.pushButton_26.x()), str(self.pushButton_26.y())
        pushButton_coords_27 = str(self.pushButton_27.x()), str(self.pushButton_27.y())

        import xml.etree.ElementTree as ET

        tree = ET.parse('yi_files\\calculator.ui')
        root = tree.getroot()
        for child in root.iter('widget'):

            for i in child.iter('widget'):
                if i.attrib['name'] == 'pushButton_8':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_8[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_8[1]
                elif i.attrib['name'] == 'pushButton_9':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_9[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_9[1]
                elif i.attrib['name'] == 'pushButton_10':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_10[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_10[1]
                elif i.attrib['name'] == 'pushButton_11':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_11[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_11[1]
                elif i.attrib['name'] == 'pushButton_12':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_12[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_12[1]
                elif i.attrib['name'] == 'pushButton_13':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_13[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_13[1]
                elif i.attrib['name'] == 'pushButton_14':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_14[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_14[1]
                elif i.attrib['name'] == 'pushButton_15':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_15[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_15[1]
                elif i.attrib['name'] == 'pushButton_16':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_16[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_16[1]
                elif i.attrib['name'] == 'pushButton_17':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_17[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_17[1]
                elif i.attrib['name'] == 'pushButton_18':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_18[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_18[1]
                elif i.attrib['name'] == 'pushButton_19':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_19[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_19[1]
                elif i.attrib['name'] == 'pushButton_20':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_20[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_20[1]
                elif i.attrib['name'] == 'pushButton_21':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_21[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_21[1]
                elif i.attrib['name'] == 'pushButton_22':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_22[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_22[1]
                elif i.attrib['name'] == 'pushButton_23':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_23[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_23[1]
                elif i.attrib['name'] == 'pushButton_24':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_24[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_24[1]
                elif i.attrib['name'] == 'pushButton_25':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_25[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_25[1]
                elif i.attrib['name'] == 'pushButton_26':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_26[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_26[1]
                elif i.attrib['name'] == 'pushButton_27':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = pushButton_coords_27[0]
                            for g in k.iter('y'):
                                g.text = pushButton_coords_27[1]
                elif i.attrib['name'] == 'lcdNumber':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = lcd_coords[0]
                            for g in k.iter('y'):
                                g.text = lcd_coords[1]
        self.file_path, ok_pressed = QInputDialog.getText(self, "Enter the path to the file directory",
            "What the path?                                                                              ")
        if ok_pressed and self.file_path != '':
                tree.write(self.file_path + '\\' + 'calculator.ui')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
