# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QMainWindow
from widgets import Slider, Label


class Ui_MainWindow(QMainWindow, object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = Slider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 660, 951, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = Slider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(980, 10, 31, 680))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label = Label(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 951, 631))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        MainWindow.setMenuBar(self.menubar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menufile.addAction(self.actionSave)
        self.menubar.addAction(self.menufile.menuAction())
        self.actionSave.triggered.connect(self.save)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                   Image"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Save "))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))

    def save(self):
        label_coords = str(self.label.x()), str(self.label.y())
        hsl_coords = str(self.horizontalSlider.x()), str(self.horizontalSlider.y())
        vsl_coords = str(self.verticalSlider.x()), str(self.verticalSlider.y())
        import xml.etree.ElementTree as ET

        tree = ET.parse('yi_files\\image_editor.ui')
        root = tree.getroot()
        for child in root.iter('widget'):

            for i in child.iter('widget'):
                if i.attrib['name'] == 'horizontalSlider':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = hsl_coords[0]
                            for g in k.iter('y'):
                                g.text = hsl_coords[1]
                elif i.attrib['name'] == 'verticalSlider':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = vsl_coords[0]
                            for g in k.iter('y'):
                                g.text = vsl_coords[1]
                elif i.attrib['name'] == 'label':
                    for j in i.iter('property'):
                        for k in j.iter('rect'):
                            for h in k.iter('x'):
                                h.text = label_coords[0]
                            for g in k.iter('y'):
                                g.text = label_coords[1]
        self.file_path, ok_pressed = QInputDialog.getText(self, "Enter the path to the file directory",
            "What the path?                                                                              ")
        if ok_pressed and self.file_path != '':
            tree.write(self.file_path + '\\' + 'image_editor.ui')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

